# Generated by Django 4.2.2 on 2023-09-27 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_cartitem_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='price',
        ),
    ]
