# Generated by Django 4.2.2 on 2023-09-27 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booked',
        ),
    ]
