# Generated by Django 4.2.2 on 2023-08-15 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='files',
            field=models.FileField(blank=True, max_length=300, null=True, upload_to='files/'),
        ),
    ]
