# Generated by Django 4.2.2 on 2023-06-21 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Couple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='Couple')),
            ],
        ),
        migrations.AlterField(
            model_name='bangle',
            name='image',
            field=models.ImageField(upload_to='Bangle'),
        ),
        migrations.AlterField(
            model_name='bracelets',
            name='image',
            field=models.ImageField(upload_to='Bracelets'),
        ),
        migrations.AlterField(
            model_name='chain',
            name='image',
            field=models.ImageField(upload_to='Chain'),
        ),
    ]
