# Generated by Django 4.2.2 on 2023-09-30 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0007_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='anklet',
            name='bg',
            field=models.ImageField(default=1, upload_to=''),
        ),
        migrations.AddField(
            model_name='anklet',
            name='product',
            field=models.CharField(default=1),
        ),
        migrations.AddField(
            model_name='ban',
            name='bg',
            field=models.ImageField(default=1, upload_to=''),
        ),
        migrations.AddField(
            model_name='ban',
            name='product',
            field=models.CharField(default=1),
        ),
        migrations.AddField(
            model_name='bangle',
            name='bg',
            field=models.ImageField(default=1, upload_to=''),
        ),
        migrations.AddField(
            model_name='bangle',
            name='product',
            field=models.CharField(default=1),
        ),
        migrations.AddField(
            model_name='brace',
            name='bg',
            field=models.ImageField(default=1, upload_to=''),
        ),
        migrations.AddField(
            model_name='brace',
            name='product',
            field=models.CharField(default=1),
        ),
        migrations.AddField(
            model_name='bracelets',
            name='bg',
            field=models.ImageField(default=1, upload_to=''),
        ),
        migrations.AddField(
            model_name='bracelets',
            name='product',
            field=models.CharField(default=1),
        ),
        migrations.AddField(
            model_name='chain',
            name='bg',
            field=models.ImageField(default=1, upload_to=''),
        ),
        migrations.AddField(
            model_name='chain',
            name='product',
            field=models.CharField(default=1),
        ),
        migrations.AddField(
            model_name='co',
            name='bg',
            field=models.ImageField(default=1, upload_to=''),
        ),
        migrations.AddField(
            model_name='co',
            name='product',
            field=models.CharField(default=1),
        ),
        migrations.AddField(
            model_name='coin',
            name='bg',
            field=models.ImageField(default=1, upload_to=''),
        ),
        migrations.AddField(
            model_name='coin',
            name='product',
            field=models.CharField(default=1),
        ),
        migrations.AddField(
            model_name='couple',
            name='bg',
            field=models.ImageField(default=1, upload_to=''),
        ),
        migrations.AddField(
            model_name='couple',
            name='product',
            field=models.CharField(default=1),
        ),
        migrations.AddField(
            model_name='diamond',
            name='bg',
            field=models.ImageField(default=1, upload_to=''),
        ),
        migrations.AddField(
            model_name='diamond',
            name='product',
            field=models.CharField(default=1),
        ),
        migrations.AddField(
            model_name='ear',
            name='bg',
            field=models.ImageField(default=1, upload_to=''),
        ),
        migrations.AddField(
            model_name='ear',
            name='product',
            field=models.CharField(default=1),
        ),
        migrations.AddField(
            model_name='earrings',
            name='bg',
            field=models.ImageField(default=1, upload_to=''),
        ),
        migrations.AddField(
            model_name='earrings',
            name='product',
            field=models.CharField(default=1),
        ),
        migrations.AddField(
            model_name='kid',
            name='bg',
            field=models.ImageField(default=1, upload_to=''),
        ),
        migrations.AddField(
            model_name='kid',
            name='product',
            field=models.CharField(default=1),
        ),
        migrations.AddField(
            model_name='mangalsutra',
            name='bg',
            field=models.ImageField(default=1, upload_to=''),
        ),
        migrations.AddField(
            model_name='mangalsutra',
            name='product',
            field=models.CharField(default=1),
        ),
        migrations.AddField(
            model_name='men',
            name='bg',
            field=models.ImageField(default=1, upload_to=''),
        ),
        migrations.AddField(
            model_name='men',
            name='product',
            field=models.CharField(default=1),
        ),
        migrations.AddField(
            model_name='neck',
            name='bg',
            field=models.ImageField(default=1, upload_to=''),
        ),
        migrations.AddField(
            model_name='neck',
            name='product',
            field=models.CharField(default=1),
        ),
        migrations.AddField(
            model_name='neckwear',
            name='bg',
            field=models.ImageField(default=1, upload_to=''),
        ),
        migrations.AddField(
            model_name='neckwear',
            name='product',
            field=models.CharField(default=1),
        ),
        migrations.AddField(
            model_name='nosepin',
            name='bg',
            field=models.ImageField(default=1, upload_to=''),
        ),
        migrations.AddField(
            model_name='nosepin',
            name='product',
            field=models.CharField(default=1),
        ),
        migrations.AddField(
            model_name='pen',
            name='bg',
            field=models.ImageField(default=1, upload_to=''),
        ),
        migrations.AddField(
            model_name='pen',
            name='product',
            field=models.CharField(default=1),
        ),
        migrations.AddField(
            model_name='pendant',
            name='bg',
            field=models.ImageField(default=1, upload_to=''),
        ),
        migrations.AddField(
            model_name='pendant',
            name='product',
            field=models.CharField(default=1),
        ),
        migrations.AddField(
            model_name='ri',
            name='bg',
            field=models.ImageField(default=1, upload_to=''),
        ),
        migrations.AddField(
            model_name='ri',
            name='product',
            field=models.CharField(default=1),
        ),
        migrations.AddField(
            model_name='ring',
            name='bg',
            field=models.ImageField(default=1, upload_to=''),
        ),
        migrations.AddField(
            model_name='ring',
            name='product',
            field=models.CharField(default=1),
        ),
        migrations.AddField(
            model_name='set',
            name='bg',
            field=models.ImageField(default=1, upload_to=''),
        ),
        migrations.AddField(
            model_name='set',
            name='product',
            field=models.CharField(default=1),
        ),
        migrations.AddField(
            model_name='women',
            name='bg',
            field=models.ImageField(default=1, upload_to=''),
        ),
        migrations.AddField(
            model_name='women',
            name='product',
            field=models.CharField(default=1),
        ),
    ]
