# Generated by Django 4.2.2 on 2023-10-25 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='image',
            field=models.ImageField(default=1, upload_to='Staff'),
            preserve_default=False,
        ),
    ]
